DROP TABLE IF EXISTS NesoOwnership;
DROP TABLE IF EXISTS Nesos;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Idols;

CREATE TABLE Users (
    Username VARCHAR(50) UNIQUE NOT NULL,
    Pincode INT NOT NULL,
    PRIMARY KEY (Username)
);

CREATE TABLE Idols (
    IdolID INT NOT NULL AUTO_INCREMENT,
    IdolName VARCHAR(50) UNIQUE NOT NULL,
    Color VARCHAR(7),
    PRIMARY KEY (IdolID)
);

CREATE TABLE Nesos (
    NesoID INT NOT NULL AUTO_INCREMENT,
    NesoName VARCHAR(100),
    IdolID INT NOT NULL,
    Size VARCHAR(10),
    ImageFileName VARCHAR(50),
    PRIMARY KEY (NesoID),
    FOREIGN KEY (IdolID) REFERENCES Idols(IdolID)
);

CREATE TABLE NesoOwnership (
    Username VARCHAR(50) NOT NULL,
    NesoID INT NOT NULL,
    FOREIGN KEY (Username) REFERENCES Users(Username),
    FOREIGN KEY (NesoID) REFERENCES Nesos(NesoID)
);

